# Generated by Django 4.2.4 on 2023-08-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='unknown')),
                ('msg', models.TextField(default='')),
                ('sendTime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chat',
            },
        ),
    ]
